#!/bin/sh
./login-hashed bob password
./login-hashed bob P@ssw0rd
./login-hashed bob Hunter2
./login-hashed bob swordfish
./login-hashed bob chandler
./login-hashed bob chariot
./login-hashed bob Beroidae
./login-hashed bob calathus
./login-hashed alice P@ssw0rd
./login-hashed alice password
./login-hashed alice Hunter2
./login-hashed alice Zoomastigina
./login-hashed alice Zwieback
./login-hashed alice Zoharite
./login-hashed alice charbroil
./login-hashed charlie Hunter2
./login-hashed charlie password
./login-hashed charlie P@ssw0rd
./login-hashed charlie swordfish
./login-hashed charlie chandler
./login-hashed charlie chariot
./login-hashed charlie tetrose
./login-hashed charlie Beroidae
./login-hashed charlie Hamidian
./login-hashed Aaru abacist
./login-hashed Aaru password
./login-hashed Aaru P@ssw0rd
./login-hashed Aaru chandler
./login-hashed Aaru chariot
./login-hashed Aaru Zwieback
./login-hashed Aaru Zoomastigina
./login-hashed Abaris cusinero
./login-hashed Abaris Zoomastigina
./login-hashed Abaris Zwieback
./login-hashed Abaris password
./login-hashed Abaris chariot
./login-hashed Abaris swordfish
./login-hashed Abaris Zythia
./login-hashed Abaris autostage
./login-hashed Abaris farweltered
./login-hashed Abaris Niobite
./login-hashed idiom legato
./login-hashed idiom Zythia
./login-hashed idiom password
./login-hashed idiom P@ssw0rd
./login-hashed idiom swordfish
./login-hashed idiom Zwieback
./login-hashed idiom chandler
./login-hashed idiom calathus
./login-hashed idiom didepsid
./login-hashed idiom Beroidae
./login-hashed negati negatron
./login-hashed negati Zwieback
./login-hashed negati password
./login-hashed negati swordfish
./login-hashed negati Zoomastigina
./login-hashed negati Zythia
./login-hashed negati Zoharite
./login-hashed negati P@ssw0rd
./login-hashed negati scoreless
./login-hashed negati Tezcucan
./login-hashed oval Ovambo
./login-hashed oval Tezcucan
./login-hashed oval scoreless
./login-hashed oval Zoharite
./login-hashed oval chandler
./login-hashed oval Hunter2
./login-hashed oval Zythia
./login-hashed oval Tezcucan
./login-hashed oval Zoharite
./login-hashed oval P@ssw0rd
./login-hashed ovarin petechiae
./login-hashed ovarin chariot
./login-hashed ovarin swordfish
./login-hashed ovarin Hunter2
./login-hashed ovarin charbroil
./login-hashed ovarin scoreless
./login-hashed ovarin Antilia
./login-hashed ovarin Hydrophis
./login-hashed ovarin calathus
./login-hashed ovarin tetrose
./login-hashed Peter pyometra
./login-hashed Peter swordfish
./login-hashed Peter autostage
./login-hashed Peter Antilia
./login-hashed Peter Hamidian
./login-hashed Peter P@ssw0rd
./login-hashed Peter Niobite
./login-hashed Peter autostage
./login-hashed Peter password
./login-hashed Peter didepsid
./login-hashed revile revictual
./login-hashed revile farweltered
./login-hashed revile didepsid
./login-hashed revile calathus
./login-hashed revile Hydrophis
./login-hashed revile tetrose
./login-hashed sarpo sarrazin
./login-hashed Sarsar Sarzan
./login-hashed Sarsar tetrose
